name: leaf_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11.9
  - scikit-fmm
  - pip:
      - numpy
      - joblib
      - matplotlib
      - open3d
      - opencv-python
      - paretoset
      - pillow
      - scikit-image
      - scikit-learn
      - scipy
